# Use a lightweight web server image
FROM nginx:alpine

# Copy the content of the local index.html to the default Nginx public folder
COPY index.html /usr/share/nginx/html

# Expose port 80
EXPOSE 80
